export const TASKS_LOADING = 'TASKS_LOADING';
export const TASKS_FAILED = 'TASKS_FAILED';
export const ADD_TASKS = 'ADD_TASKS';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const TASKS_UPDATED = 'TASKS_UPDATED';
export const TASKS_UPDATE_COMPLETE = 'TASKS_UPDATE_COMPLETE';
